export const configKeyboard = [
  { id: '(', label: '(', isAdvancedKey: true },
  { id: '+', label: '+', isAdvancedKey: false },
  { id: '-', label: '-', isAdvancedKey: false },
  { id: '*', label: '*', isAdvancedKey: false },
  { id: '/', label: '/', isAdvancedKey: false },
  { id: ')', label: ')', isAdvancedKey: true },
  { id: '1', label: '1', isAdvancedKey: false },
  { id: '2', label: '2', isAdvancedKey: false },
  { id: '3', label: '3', isAdvancedKey: false },
  { id: '4', label: '4', isAdvancedKey: false },
  { id: '5', label: '5', isAdvancedKey: false },
  { id: 'delete', icon: 'Delete', isAdvancedKey: false },
  { id: '6', label: '6', isAdvancedKey: false },
  { id: '7', label: '7', isAdvancedKey: false },
  { id: '8', label: '8', isAdvancedKey: false },
  { id: '9', label: '9', isAdvancedKey: false },
  { id: '0', label: '0', isAdvancedKey: false },
  { id: 'enter', icon: 'Enter', isAdvancedKey: false },
];
